- name: 'Medicine Nav'
  position: [7.22, 3.29]
  orientation: [-.002, .002, .001, .9999]
  height: .6
- name: 'Medicine Table Align'
  position: [7.75, 3.31]
  orientation: [-.002, .002, .001, .9999]
  height: .6
- name: 'Snack Nav'
  position: [7.19, 4.15]
  orientation: [-.002, .002, .001, .9999]
  height: .6
- name: 'Snack Table Align'
  position: [7.67, 4.15]
  orientation: [-.002, .002, .001, .9999]
  height: .6
- name: 'Couch Dropoff'
  position: [4.40, 2.72]
  orientation: [-.002, .002, .9948, -.101]
  height: 0.0
- name: 'Dining Table Nav'
  position: [5.16, 2.55]
  orientation: [-.0049, -.0011, .708, .706]
  height: .3
- name: 'Dining Table Table Align'
  position: [5.15, 2.83]
  orientation: [-.0049, -.0011, .708, .706]
  height: .3
